# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4469e673995a004de2681f840ae7edf1ed8e983bd640f9b917dcd1b531ecaccb5f262497fdc3134ae6887ae87a0940deea96dd4d444c60753d2f448e7a035f1d

test:
  secret_key_base: 6d5d7fa5567903051b59c50dc8a577ea170f31777a9c5988eece79fcc05b9a7f2d21d3266cf04531b7e63930f20834b984477389d8607d18d3144e5ffd7c4963

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
